import Head from "next/head";
import { ReactElement, useState } from "react";
import { MainLayout } from "@/layout/Main";
import ChatBot from "@components/ChatBot";
import Image from "next/image";
import ChatPoster from "@images/ChatPoster.jpg";
export default function Home() {
  const [start, setStart] = useState(false);
  return (
    <>
      <Head>
        <title>MindMeet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logoMindMeet.png" />
      </Head>
      <div className=" flex gap-4 justify-center items-center h-screen  ">
        <div className="w-[600px]  h-[700px] -mt-[120px] rounded-lg overflow-hidden">
          <Image
            src={ChatPoster}
            alt="Mental Health Poster"
            style={{ width: "620px", height: "740px" }}
          />
        </div>
        <div className="w-[700px] h-[700px]  -mt-[120px]">
          {start ? (
            <ChatBot />
          ) : (
            <div className="w-full h-full flex flex-col space-y-6 justify-center items-center">
              <p className="text-2xl font-bold  uppercase mb-10">
                Break the silence, find support with MindMeet
              </p>

              <p
                onClick={() => setStart(true)}
                className="py-2 px-6 rounded-md bg-mainC2 text-white animate-bounce cursor-pointer hover:animate-none hover:bg-mainC transition-all delay-100"
              >
                Start the Test Now
              </p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
